# TensorFlow 基础
- TensorFlow基础结构
- 创建常量、变量
- TensorFlow与numpy
- 容器的创建等

In [3]:
import tensorflow as tf

### 1.创建变量
每次创建变量在使用之前都要对变量进行初始化。

In [9]:
a = 3
# 创建一个变量
w = tf.Variable([[0.5,1.0]])
x = tf.Variable([[2.0],[1.0]]) 

y = tf.matmul(w, x)  


#全局变量初始化
init_op = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init_op)
    print (y.eval())

[[ 2.]]


### 2.TensorFlow vs numpy

tensorflow很多操作跟numpy有些类似的

* tf.zeros([3, 4], int32)

* tf.zeros_like(tensor)

* tf.ones([2, 3], int32) 

* tf.ones_like(tensor)

* tensor = tf.constant([1, 2, 3, 4, 5, 6, 7])

* tensor = tf.constant(-1.0, shape=[2, 3])                                           

* tf.linspace(10.0, 12.0, 3, name="linspace")

* tf.range(start, limit, delta)

In [5]:
#生成的值服从具有指定平均值和标准偏差的正态分布
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# 洗牌
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# 每一次执行结果都会不同
# 创建对话
sess = tf.Session()

print (sess.run(norm))
print (sess.run(shuff))

[[-3.56395006  1.88093901 -0.71911514]
 [-2.99759626  1.89863086 -4.54589462]]
[[1 2]
 [3 4]
 [5 6]]


### 3.加法与赋值操作

In [20]:
state = tf.Variable(0)
# 加法操作，state + 常量1
new_value = tf.add(state, tf.constant(1))
# 赋值操作，把new_value 赋值给state
update = tf.assign(state, new_value)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(state))    
    for _ in range(3):
        sess.run(update)
        print(sess.run(state))

0
1
2
3


### 4.numpy转换成TensorFlow变量

In [21]:
import numpy as np
a = np.zeros((3,3))
ta = tf.convert_to_tensor(a)
with tf.Session() as sess:
     print(sess.run(ta))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


### 5.TensorFlow常量运算

In [26]:
a = tf.constant(5.0)
b = tf.constant(10.0)

x = tf.add(a, b, name="add")
y = tf.div(a, b, name="divide")

with tf.Session() as sess:
    print("a =", sess.run(a))
    print("b =", sess.run(b))
    print("a + b =", sess.run(x))
    print("a/b =", sess.run(y))

a = 5.0
b = 10.0
a + b = 15.0
a/b = 0.5


### 6.容器的使用
先创建一个容器，并指定容器要放的东西，最后往容器中添加所需要的东西

In [24]:
input1 = tf.placeholder(tf.float32)
input2 = tf.placeholder(tf.float32)
# 先定义操作，里面还没有实际的值
output = tf.multiply(input1, input2)
with tf.Session() as sess:
    print(sess.run([output], feed_dict={input1:[7.], input2:[2.]}))

[array([ 14.], dtype=float32)]
